### ISSUE TITLE
Add `required` attributes on CardSettings widgets

### ISSUE THREAD

**Issue by arthurgustin** [codegrue/card_settings#10]
I would like to have the possibility to have nullable fields and required fields in my form. Currently I does this with setting validator to null or not, but the user does not have a visual feedback untill pressing the save or next button (which validate all fields on pressed)

If `required: true`, I want my label to have a red star after the text, example:

  - Address Line 1*: _____

If `required: false`, no red star, example:

  - Address Line 1: _____

I can create a MR for this

**Comment by codegrue** [comment]
set `autovalidate` to `true` and feedback will be immediate.

The required property is a good idea. I am thinking `requiredIndicator` (widget) that you can pass anything you want to appear there, and asterisk or an icon, for example.

**Comment by arthurgustin** [comment]
@codegrue Ues but I want users to know if the field is required before they have to type anything, like we used to have in html forms

**Comment by codegrue** [comment]
Added in 0.1.12
