### ISSUE TITLE
Picker Strange behavior

### ISSUE THREAD

**Issue by rubgithub** [codegrue/card_settings#101]
I don't know when exactly this starts to happen, but I believe that was after upgrade flutter and all packages. 

Any idea how to fix this?

![test](https://user-images.githubusercontent.com/3399476/82130167-e587eb00-9796-11ea-855f-087178159f66.gif)

**Comment by codegrue** [comment]
Does this only happen with two items?

**Comment by codegrue** [comment]
Found the bug and fixed on flutter_material_pickers. Will be fixed in the next release 1.9.0
