### ISSUE TITLE
CardSettingsListPicker visual bug and Selection failure

### ISSUE THREAD

**Issue by rubgithub** [codegrue/card_settings#102]
version: 1.9.1

```
values: ['Store1', 'Store2'],
options: const ['Store1', 'Store2'],
initualValue: 'Store1',
```

════════ Exception caught by gesture ════════════════════
RangeError (index): Invalid value: Not in range 0..1, inclusive: -1
══════════════════════════════════════════════

![SceAppv1 32a](https://user-images.githubusercontent.com/3399476/82486324-aa452f00-9aaa-11ea-93e8-a87a31c2cc66.gif)

**Comment by codegrue** [comment]
Fixed in 1.9.2
