### ISSUE TITLE
How to disable text edit?

### ISSUE THREAD

**Issue by robertoltrocha** [codegrue/card_settings#104]
I´d like to disable text edit and enable(false) is not woking.
this form I´d like to set readonly and enable/disabled in runtime

this need applies to the other types of fields(DateTimePicker), only for reading.

thank you.

 CardSettingsText(
      key: _tipoCertificadoKey,
      label: 'Tipo: ',
      enabled: false,
      autofocus: false,
      labelWidth: 50,
      contentAlign: TextAlign.left,
      hintText: 'something cute...',
      initialValue:
          widget.snapshot.tipoCertificadoAvulso.tipoCertificadoAvulsoDescricao,
      //requiredIndicator: Text('*', style: TextStyle(color: Colors.red)),
      autovalidate: _autoValidate,
      validator: (value) {
        if (value == null || value.isEmpty) return 'Name is required.';
        return null;
      },
      onSaved: (value) => widget.snapshot.tipoCertificadoAvulso
          .tipoCertificadoAvulsoDescricao = value,
      onChanged: (value) {
        setState(() {
          widget.snapshot.tipoCertificadoAvulso.tipoCertificadoAvulsoDescricao =
              value;
        });
      },
    );

**Comment by codegrue** [comment]
Fix will be deployed in version 1.9.5
