### ISSUE TITLE
 Getter not found: 'obscuringCharacter' when building for windows desktop

### ISSUE THREAD

**Issue by nirvan-odb** [codegrue/card_settings#107]
`Error: Getter not found: 'obscuringCharacter'.
                  _show ? widget.secret : RenderEditable.obscuringCharacter * widget.secret.length,`
When running `flutter run -d windows`.

This seems to be originating from a dependency on the package [https://pub.dev/packages/flutter_cupertino_settings](https://pub.dev/packages/flutter_cupertino_settings). However, they recently fixed this issue. That can be seen [here](https://github.com/matthinc/flutter_cupertino_settings/issues/20). 

I also noticed that the card_settings package supposedly fixed this issue already as well [in this update](https://github.com/codegrue/card_settings/commit/532a4935fc259d29b8d15693622e0d5191ce1369)

Can you guys help me understand why I am getting this compiler error still then?

My flutter doctor says this:
`[√] Flutter (Channel master, 1.19.0-3.0.pre.13, on Microsoft Windows [Version 10.0.18362.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.0)
[√] Android Studio (version 3.0)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (3 available)
`

and I am using card_settings version ^1.9.3

**Comment by nirvan-odb** [comment]
I tried deleting the .packages file as well as other files, I ran flutter clean and still no luck. In the error message, I also see that the error originates from the flutter_cupertino_settings-0.3.0.

`AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_cupertino_settings-0.3.0/lib/widgets/secret.dart(41,58): error G3824A48C: Getter not    
found: 'obscuringCharacter'. `

How can I force it to use the 0.3.1 version? I am not sure why it is using the older version.

**Comment by codegrue** [comment]
This is due to the cupertino_settings project that it depends on. That is being fixed currently.

**Comment by codegrue** [comment]
I will release an update to 0.3.1 but there is an issue with another package also. Waiting for that fix.

**Comment by codegrue** [comment]
BTW this error is only on the beta channel. Stable is fine.

**Comment by nirvan-odb** [comment]
It is also actually on the master channel as well, since that is what flutter recommends to be on when building for desktop.

To temporarily work around the issue, I went into the appdata folder where my flutter packages are located locally and changed the pubspec.yaml file of the card_settings folder to import flutter_cupertino_settings ^0.3.1 instead of ^0.3.0

Let me know if I should close this issue for now as it's only a small one when building for desktop in flutter master channel.

**Comment by codegrue** [comment]
The fix is checked in I just need to deploy the new version. There is one other bug outstanding that I want to wrap up first. Probably will go out tonight.,

**Comment by codegrue** [comment]
Fixed in 1.9.4
