### ISSUE TITLE
new version label.width its working for only text type card settings items

### ISSUE THREAD

**Issue by NTMS2017** [codegrue/card_settings#109]
new version label.width its working for only text type card settings properties it doesn't work other items such as picker etc.

**Comment by codegrue** [comment]
Can you describe how this is not working maybe with a screen shot? I tried width of 100, 200, and 300 and all seems to work correctly.

**Comment by codegrue** [comment]
I think I see, the global width works, but other fields lack an individual labelWidth. Correct?

**Comment by codegrue** [comment]
Fix coming on version 1.9.7
