### ISSUE TITLE
Title for CardSettingsColorPicker is english. is not localize

### ISSUE THREAD

**Issue by robertoltrocha** [codegrue/card_settings#110]
Hello,
Here is a suggestion for improvements.
It is not possible to put the title in other languages without having to change the code.
you can put as variable the title dialog.
In portuguese ("Cor para ") but the best is only Cor Background.

There is also no white color as an option or a buttom to clear the color.

![WhatsApp Image 2020-06-07 at 17 55 26](https://user-images.githubusercontent.com/30963205/83979953-634b9c00-a8e8-11ea-9511-ecd1ae4197fe.jpeg)

**Comment by codegrue** [comment]
Removing color prefix in version 1.9.6. 

The lack of white is an issue with the `flutter_colorpicker` package that this uses. Please lodge a feature request there and `card_settings` will inherit that once added.

https://github.com/mchome/flutter_colorpicker
