### ISSUE TITLE
Feature request: add option in CardSettingsSelectionPicker to accept an id and value for each options

### ISSUE THREAD

**Issue by kuromukira** [codegrue/card_settings#119]
Currently, the CardSettingsSelectionPicker only accepts a list of string with the initial value of string. The default Flutter dropdown item supports for {id, value} options and the selected value as the id. It would be great if you'd be able to support this. Thanks

**Comment by codegrue** [comment]
This is on my wishlish too to make it work like the native controls. Probably in version 2.0 since it's a pretty big breaking change.

**Comment by codegrue** [comment]
Note there is an values list that can be used to have different values and options. It's just not a single object like the way dropdown works. That will be the breaking change. But you can do this today. Look at how it's done in the Pony example.

**Comment by kuromukira** [comment]
Will take a look at it. Thanks.
