### ISSUE TITLE
Incompatible intl version

### ISSUE THREAD

**Issue by arthurgustin** [codegrue/card_settings#12]
Hi, sorry to bother you, but I get this message when trying to build my apk:

`ERR : Because every version of card_settings depends on intl ^0.15.7 and every version of flutter_localizations from sdk depends on intl 0.15.6, card_settings is incompatible with flutter_localizations from sdk.`

Do you mind downgrading the intl version or is there another solution ?

**Comment by codegrue** [comment]
Will ^0.15.6 work or do I have to explicitly say 0.15.6?

**Comment by arthurgustin** [comment]
@codegrue I think `^0.15.6` is fine

**Comment by codegrue** [comment]
took me a while to find this. is this the one?

https://github.com/flutter/flutter/tree/master/packages/flutter_localizations

no dartpub package makes it's stability questionable. I would think they should support the latest intl but they have over 3000 issues. Did you add it to your project locally?

**Comment by codegrue** [comment]
Are you using the master branch? Look at this code it's using intl 0.15.7:

https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml

**Comment by arthurgustin** [comment]
Yes I saw I tried to upgrade (even with force option) but it doesn't change anything, can you build an apk ?

**Comment by codegrue** [comment]
Yes I am building one tonight I will downgrade it

**Comment by codegrue** [comment]
this is what i'm getting now: :)

Because every version of card_settings from path depends on intl 0.15.6 and every version of flutter_localizations from sdk depends on intl 0.15.7, card_settings from path is incompatible with flutter_localizations from sdk.
