### ISSUE TITLE
add new type of CardSettings

### ISSUE THREAD

**Issue by robertoltrocha** [codegrue/card_settings#121]
Hi,

This is configuration plugging. Is it possible to add a card to choose a user image and show it in the center? With its new version of your pluging I was unable to insert different types of widgets between CardSettingWidgets. See the example of the user image.
When I tapped hover the image I can choose the new image and save it.
thanks
![Capturar](https://user-images.githubusercontent.com/30963205/86974665-1cea9680-c14d-11ea-88fd-80920db983bc.PNG)

**Comment by robertoltrocha** [comment]
there are CardSettingsFilePicker and solve it.
thanks

**Comment by codegrue** [comment]
You need to use CardSettingsField and provide your custom item for the child.
