### ISSUE TITLE
Feature request: Add parameter to customize the scroll physics

### ISSUE THREAD

**Issue by kuromukira** [codegrue/card_settings#123]
It feels weird that only the form card can be scrolled (even though there's only 2 fields) and the rest of the screen can't. It would be nice to be able to change the scroll physics for the CardSettingsForm

**Comment by codegrue** [comment]
Can you post a screen shot? Not sure I'm following what you mean.

**Comment by codegrue** [comment]
Ability to turn scrolling off will be included in release 1.11.1. You will need to wrap it in some kind of scrollable widget, such as SingleChildScrollable, to restore/customize scrolling. Note this only work with the Material version, since the Cupertino form has scrolling baked in.
