### ISSUE TITLE
Help Required | List Picker | OnChanged

### ISSUE THREAD

**Issue by NiranjanShah** [codegrue/card_settings#124]
Can you please guide me how to use async function in the ListPicker onChanged event.

Thanks in advance

**Comment by NiranjanShah** [comment]
Sorry wasnt' aware that using onChanged: (value) async { } is allowed

**Comment by NiranjanShah** [comment]
calling async function in onValueChanged  and then setting CardSettingsText value does not change immediately. it changes after  scrolling and coming back to same position.

onChanged: (value) async {
         await getState4City(value);
}

getState4City(String city) async{
//getting state over here
then setting the state value and calling setstate over here
}

**Comment by codegrue** [comment]
Can you post the code? Most of these controls manage state internally. The value property is the initial state, so changing it won't change the control value. You might have to provide a customer controller to achieve what you want to do.

**Comment by codegrue** [comment]
Closing unless more details are provided.
