### ISSUE TITLE
Custom Widgets 

### ISSUE THREAD

**Issue by rubgithub** [codegrue/card_settings#125]
https://pub.dev/packages/card_settings#custom-widgets

```
class CardSettingsHeader extends StatelessWidget implements CardSettingsWidget {
  ...
}
```

When creating a Custom Widget lint complains: avoid_implementing_value_types (https://dart-lang.github.io/linter/lints/avoid_implementing_value_types.html)

What's the drawback about this?

**Comment by codegrue** [comment]
This looks to be related to overloading comparison operators. Can you post more of your code where the warning is being displayed?

**Comment by rubgithub** [comment]
```
class CustomCardSettingsWidget extends StatelessWidget
    implements
        // ignore: avoid_implementing_value_types
        CardSettingsWidget {
  const CustomCardSettingsWidget({
    Key key,
    this.showMaterialonIOS,
    this.visible,
    this.card,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return card;
  }

  @override
  final bool showMaterialonIOS;

  @override
  final bool visible;

  final Widget card;
}
```

**Comment by codegrue** [comment]
I don't get this error so you must have a more restrictive linter setting.
