### ISSUE TITLE
Card Settings currency error..

### ISSUE THREAD

**Issue by kiditz** [codegrue/card_settings#126]
I found a bug in CardSettingsCurrency.dart there is error when i put value with symbol ',' e.g 2,500.00. when i press form save.. there is error found in your code. your double parse was unable to convert ',' symbol

// perform explicit parsing on the value as a string
if (T.toString() == 'double') return double.parse(value.toString()) as T;

Unhandled Exception: FormatException: Invalid double
E/flutter ( 3284): 2,500.00
E/flutter ( 3284): #0      double.parse  (dart:core-patch/double_patch.dart:112:28)
E/flutter ( 3284): #1      intelligentCast 
package:card_settings/helpers/converter_functions.dart:23
E/flutter ( 3284): #2      CardSettingsCurrencyState._safeOnSaved 
package:card_settings/…/numeric_fields/card_settings_currency.dart:186
E/flutter ( 3284): #3      FormFieldState.save

**Comment by codegrue** [comment]
Are you on the latest version? This was changed to parse a number before the intelligentCast gets called.

**Comment by codegrue** [comment]
Fixed in 1.12.1
