### ISSUE TITLE
how to apply cardTheme

### ISSUE THREAD

**Issue by jinfagang** [codegrue/card_settings#129]
can not find such a param

**Comment by rubgithub** [comment]
There's no specific parameter, but you can can use:

```
Theme(
    data: Theme.of(context).copyWith(
      primaryTextTheme: TextTheme(
        headline6: TextStyle(color: Colors.lightBlue[50]), // app header text
      ),
      inputDecorationTheme: InputDecorationTheme(
        labelStyle: TextStyle(color: Colors.deepPurple), // style for labels
      ),
    ),
    child: CardSettings(
      ...
    ),
  )

```

You can find more details in the documentation [https://pub.dev/packages/card_settings](https://pub.dev/packages/card_settings )

**Comment by rubgithub** [comment]
There's no parameter, its in `ThemeData`

```
Theme.of(context).copyWith(
  cardTheme:
...
```

**Comment by jinfagang** [comment]
@rubgithub  thanks for your reply! BTW, how to add an image raw in settings ? Like add an image in trailing widget in listtile.

**Comment by rubgithub** [comment]
I think you have to create your own header:

```
header: CardSettingsHeader(
  //label: 'Heaer Label',
  child: MyHeaderWidget()
),
```

**Comment by rubgithub** [comment]
Well, if I understood your question, basically you have to create your own header:

```
header: CardSettingsHeader(
  //label: 'Heaer Label',
  child: MyHeaderWidget()
),
```

**Comment by jinfagang** [comment]
@rubgithub  Not add header above section, I want a single setting raw with Image in trailing, such as let user change their avatar. Does it can be supported?

**Comment by codegrue** [comment]
Would the file upload control set to image not work for this?

**Comment by jinfagang** [comment]
@codegrue  Does card_settings provide such an UI raw for quickly support? BTW, any way to change the divider between raws of card settings?
And the style of chip in multi picker widget?

**Comment by codegrue** [comment]
You can use the CardSettingsWidget to wrap any content you want. The build in ones work the way they want because they are consistent shortcuts.

You can change the divider. The example shows how to do that. 

There is another issue logged for chip styling
