### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by peter369** [codegrue/card_settings#133]
Everytime I try to select a value from CardSettingsNumberPicker and CardSettingsListPicker I get the error: "Failed assertion: boolean expression must not be null" in the pop-up window that is supposed to contain my values, I'm using the code below:

`CardSettingsListPicker(
                        label: 'Status',
                        initialValue: 'U',
                        options: <String>[
                          'Earth',
                          'Unicorn',
                          'Pegasi',
                          'Alicorn'
                        ],
                        values: <String>['E', 'U', 'P', 'A'],
                        icon: Icon(Icons.star),
                        
                      ),`

This only happens when using Material theme, when using iOS theme it's working well.

Please any help is welcome.

![2020-08-27 at 12 31 AM](https://user-images.githubusercontent.com/30994776/91388335-b274df00-e7fc-11ea-9084-4ee4163fc2d1.png)
![2020-08-27 at 12 30 AM](https://user-images.githubusercontent.com/30994776/91388339-b43ea280-e7fc-11ea-9bf3-cceb127b2063.png)

**Comment by rubgithub** [comment]
Try this:
`initialValue: 'Unicorn',`

**Comment by peter369** [comment]
Hello, I've tested with your suggestion but it still not working...

I've downloaded the example code and executed in simulator but listPicker and NumberPicker shows the same error message:

Failed assertion: boolean expression must not be null

Thanks for your help.

**Comment by rubgithub** [comment]
Can you post your `CardSettingsListPicker` widget code?

**Comment by codegrue** [comment]
This was a bug in the materials picker package that was fixed. Source code is there. I might have to push out an update to this package to use the latest there.

**Comment by codegrue** [comment]
Fixed in 1.12.2
