### ISSUE TITLE
Update cupertino_icons dependency

### ISSUE THREAD

**Issue by enricobenedos** [codegrue/card_settings#134]
Good morning,

I would like to update `cupertino_icons` dependency to `1.0.0` but at the moment I cannot due that due to:
```
Because card_settings 1.12.2 depends on cupertino_icons ^0.1.3 and no versions of card_settings match >1.12.2 <2.0.0, card_settings ^1.12.2 requires cupertino_icons ^0.1.3.
```

Is there the possibility to update the dependency?

Thank you

**Comment by codegrue** [comment]
Unfortunately I cannot make this update until the dependency package `flutter_cupertino_settings` does this.

**Comment by codegrue** [comment]
Removed the dependency from CardSettings as it's not actually used. The limitation now is the dependency package.

**Comment by enricobenedos** [comment]
It seems that now the packages has been updated and supports `cupertino_icons 1.0.0`
