### ISSUE TITLE
How to use CardSettingsCheckboxPicker

### ISSUE THREAD

**Issue by calvinsug** [codegrue/card_settings#135]
I try to use this code

`CardSettingsCheckboxPicker(
                    label: "I have read and agree for this term and agreement",
                    initialValues: ["false"],
                    onChanged: (value) => setState(() => _confirm = true),
                  )`

but the result is empty and the checkbox shape is weird. When i click to check it, it gives me red error screen.

What am i doing wrong here?

**Comment by robertoltrocha** [comment]
Hi,
try to change this line.
_confirm = value

```
CardSettingsCheckboxPicker( label: "I have read and agree for this term and agreement", initialValues: ["false"], onChanged: (value) => setState(() => _confirm = **VALUE**), )

but the result is empty and the checkbox shape is weird. When i click to check it, it gives me red error screen.

What am i doing wrong here?
```

**Comment by codegrue** [comment]
CardSettingsCheckboxPicker is a list of checkboxes in a dialog. I think you want CardSettingsSwitch instead.

The value returned from CardSettingsCheckboxPicker i a list of checked options that were true. Please see the project example code for how these are used.
