### ISSUE TITLE
error read image from instagram fisrt time open CardSettingsFilePicker()

### ISSUE THREAD

**Issue by robertoltrocha** [codegrue/card_settings#140]
When I choose an image from the instagram library the first time I open the settings screen, the file the image is not read in its entirety and therefore the image cannot be displayed and the app crashes.

This issue only happens when the app is clean, without data and is installed for the first time and when the user chooses an image from the instagram library.

If I upload an image from the android library and then choose an instagram image the error does not happen. Only if the app has all cache data removed.

You can see that there is a difference between the file size shown in the file_picker cache folder and the file size shown in the app.

I didn't choose the image type to show so as not to have the crash

**you can similator this issue with your exemple, just choose an instagram image in first time when you open your app**

```
 CardSettingsFilePicker(
                visible: isPermission,
                maxThumbnailHeight: 100.0,
                showMaterialonIOS: true,
                unattachDialogTitle: "Deseja excluir essa imagem?",
                unattachDialogConfirm: "Sim",
                unattachDialogCancel: "Não",
                icon: Icon(Icons.photo),
                label: '',
                fileExtension: "jpg",
                //fileType: FileType.image,
                initialValue: model.photo,
                onChanged: (value) async {
                
                },
              ),
```

![Capturar5](https://user-images.githubusercontent.com/30963205/95693138-2fb7b000-0c01-11eb-9719-f2e7df6cc55e.PNG)

![Capturar4444](https://user-images.githubusercontent.com/30963205/95693161-4c53e800-0c01-11eb-98bf-dbe4cfcd093a.PNG)

**Comment by codegrue** [comment]
Can you please post this issue to the file_picker project? Card Settings just uses that library to deliver this functinality.

**Comment by codegrue** [comment]
Upgraded the file picker version in 1.15.0. Please test and confirm working or still broken
