### ISSUE TITLE
CardSettingsRadioPicker

### ISSUE THREAD

**Issue by acamenhas** [codegrue/card_settings#141]
Hello,
I'm using cart_settings for a couple of days and I have 2 questions related to the CardSettingsRadioPicker:

**_1) Can I use a "id/label" pair so it's easy to get the id of the selected element? How do you do now to get the selected id?_ done**
2) Are you planning to create an input filter that can help for long lists?

Thank you for all your effort on this lib!
Artur

**Comment by codegrue** [comment]
Yes you need to provide a list of options and values separately:

      options: <String>['Male', 'Female'],
      values: <String>['M', 'F'],

A future revision will allow a complex options instead of this pattern.
