### ISSUE TITLE
Card Settings in Flutter Awesome 👏 

### ISSUE THREAD

**Issue by CoolONEOfficial** [codegrue/card_settings#143]
https://github.com/Solido/awesome-flutter/pull/765

@codegrue 
Now you can add badge :)

 <a href="https://stackoverflow.com/questions/tagged/flutter?sort=votes">
  <img alt="Awesome Flutter" src="https://img.shields.io/badge/Awesome-Flutter-blue.svg?longCache=true&style=flat-square" />
 </a>
 
 ``` 
<a href="https://github.com/Solido/awesome-flutter">
    <img alt="Awesome Flutter" src="https://img.shields.io/badge/Awesome-Flutter-blue.svg?longCache=true&style=flat-square" />
</a>
```

**Comment by codegrue** [comment]
Thanks. (Although I don’t see it on the list)…
