### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by graemebond** [codegrue/card_settings#147]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by nhn12** [comment]
The same issue with me, I can't build file apk with error "file_picker"

**Comment by codegrue** [comment]
Is this iOS or Android?

**Comment by graemebond** [comment]
> Is this iOS or Android?

Android

**Comment by Blacktoviche** [comment]
I have the same issue on android . is there any solution?

**Comment by rubgithub** [comment]
There's a similar issue reported here:
https://github.com/miguelpruivo/flutter_file_picker/issues/458

> solved! just changed the android plugin gradle version to 3.6.4 in build.gradle and gradle version to 5.6.4 in gradle-wrapper.properties

**Comment by codegrue** [comment]
I am able to run it fine on Android. It has to be something with your configuration but I'm not sure what. Did you try running the example bundled with the project?

**Comment by codegrue** [comment]
This is a gradle version issue. the example is fixed in 1.15.0
