### ISSUE TITLE
Form validation not working

### ISSUE THREAD

**Issue by enricobenedos** [codegrue/card_settings#157]
Good morning,

I'm trying to use the function to validate all my form but seems that the `currentState` property is empty.
This is the code I use to validate the entire form:
```dart
if (!_formKey.currentState.validate())
```
and this is the generated exception:
```console
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'validate' was called on null.
Receiver: null
Tried calling: validate()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ContactsPageState.build.<anonymous closure>
package:wamii_app/pages/contacts_page.dart:163
```

How to correctly validate my entire form?

**Comment by codegrue** [comment]
This works in the example. Please compare that to your app to see what might be different.

**Comment by enricobenedos** [comment]
Sorry I thought that `Form()` widget was already included on `CardSettings()` one and it was sufficient to pass the key. Now I wrap with a `Form()` as in the example and it works. Thank you
