### ISSUE TITLE
error: Undefined name 'ScaffoldMessenger'. (undefined_identifier at [flutter_form] lib/plumbing/scaffold.dart:66)

### ISSUE THREAD

**Issue by NTMS2017** [codegrue/card_settings#161]
I created a empty flutter project and replace your example data and I am getting error on:

error: Undefined name 'ScaffoldMessenger'. (undefined_identifier at [flutter_form] lib/plumbing/scaffold.dart:66)

But couldn't find anything related to ScaffoldMessenger in your code. Please help.

**Comment by codegrue** [comment]
ScaffoldMessenger is in the code that displays the toast when a value changes. You can probably delete any references to that and your code should work.
