### ISSUE TITLE
Build Errors for iOS

### ISSUE THREAD

**Issue by kerbo** [codegrue/card_settings#168]
I pulled your package into my relatively new project and at first use (running on iOS emulator), I got these errors:

./flutter/.pub-cache/hosted/pub.dartlang.org/card_settings-2.0.1/lib/widgets/picker_fields/card_settings_checkbox_picker.dart:115:7: Error: No named parameter with the name 'selectedItems'.
      selectedItems: value,
      ^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_material_pickers-2.1.1/lib/helpers/show_checkbox_picker.dart:8:6: Context: Found this candidate, but the arguments don't match.

void showMaterialCheckboxPicker({
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/card_settings-2.0.1/lib/widgets/picker_fields/card_settings_selection_picker.dart:173:7: Error: No named parameter with the name 'selectedItem'.
      selectedItem: option,
      ^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_material_pickers-2.1.1/lib/helpers/show_selection_picker.dart:8:6: Context: Found this candidate, but the arguments don't match.
void showMaterialSelectionPicker({

Not sure what I'm missing.

**Comment by hoaian09011991** [comment]
same issue

**Comment by codegrue** [comment]
Fixed in 2.0.2
