### ISSUE TITLE
Feature request: CardSettingsListPicker - selected item text color

### ISSUE THREAD

**Issue by AdamBrodin** [codegrue/card_settings#172]
Hello there!

Would it be possible to be able to change the color of the preview/currently selected list item from a list picker? As of right now the only color available seems to be black.

![image](https://user-images.githubusercontent.com/39487269/132005105-5821e89a-c51a-4f06-a4a9-93fbf73743fd.png)

**Comment by codegrue** [comment]
All the colors are controlled by themes.  See the example and readme for how to do this.

**Comment by AdamBrodin** [comment]
> All the colors are controlled by themes. See the example and readme for how to do this.

My fault, I've tried to change various colors on the theme before but I must have missed it.  Solved it now.
For anyone with the same issue, here's the specific theming settings that changes it:

`textTheme: TextTheme(
          subtitle1: TextStyle(color: Colors.red[800]))`
