### ISSUE TITLE
Upgrade dependency to intl ^0.18.1 

### ISSUE THREAD

**Issue by rubgithub** [codegrue/card_settings#182]
Hi there, 
It is possible to fix this?
`Because every version of my_package from path depends on intl ^0.18.1 and card_settings 3.3.0 depends on intl ^0.17.0, my_package from path is incompatible with card_settings 3.3.0.`

**Comment by eloidramsess** [comment]
I have the same problem, could you update the dependency please .. Thank you very much..

**Comment by codegrue** [comment]
I'm challenged in that a package, pattern_formatter,  that this library uses has not been upgraded, so it's blocking this.

**Comment by codegrue** [comment]
Try version 3.4.0.

**Comment by lublak** [comment]
@codegrue I don't think there will be any more updates. The last update was 2 years ago.
Maybe you could use an alternative here?
Something I found:
https://pub.dev/packages/mask_text_input_formatter

**Comment by Miloune** [comment]
There is a new version https://github.com/hnvn/flutter_pattern_formatter/releases/tag/v3.0.0
Maybe it can help?

**Comment by codegrue** [comment]
Published fixes in version 3.5.0
