### ISSUE TITLE
 Picker Dialog start from DownSide  CardSettingsListPicker

### ISSUE THREAD

**Issue by nsharma098** [codegrue/card_settings#29]
If PickerDialog are not initiated with Some Value or initiated with some another value that is not present in OptionsList then it Start from the lowest element, and here is the solution

`https://github.com/nsharma098/card_settings`

and problem is
![screenshot_20180920-190649](https://user-images.githubusercontent.com/26966630/45822230-a0cd5780-bd08-11e8-8cbb-ef59c388a789.png)
![screenshot_20180920-190645](https://user-images.githubusercontent.com/26966630/45822227-9f9c2a80-bd08-11e8-92d6-f48f85714afa.png)

@codegrue

**Comment by codegrue** [comment]
Can you make sure your "select one" text is a placeholder decoration and submit a pull request?

**Comment by nsharma098** [comment]
@codegrue  I donot want to show "Select One" to the User

**Comment by codegrue** [comment]
first items fixed on 1.2.1
