### ISSUE TITLE
Feature request: disable a CardSetting widget

### ISSUE THREAD

**Issue by arthurgustin** [codegrue/card_settings#33]
Hi there !
I'm in a situation where I want to disable an input (not hiding it) by making it grey and disable any interactions: if it's a ListPicker, the popUp should not pop when I tap on the widget, if it's a text field I don't want to show the keyboard, etc...
Have you ever considered it ?

Regards

**Comment by codegrue** [comment]
I'm looking for contributors to this project. Would you like to have the ability to push changes?

**Comment by arthurgustin** [comment]
I would love too but i'm already torn apart by two other projects and this feature is not a priority...

**Comment by codegrue** [comment]
CardSettingsText already supports this (through Flutter's TextFormField widget) but to be honest I see no visual change. I guess the label should become grey. Seems like making all controls do this would take some time.

**Comment by AppleEducate** [comment]
@arthurgustin  is this still needed?

**Comment by arthurgustin** [comment]
Hi, I'm not involved in a flutter project anymore so I don't need this

Le ven. 15 févr. 2019 à 21:52, Rody Davis <notifications@github.com> a
écrit :

**Comment by AppleEducate** [comment]
Fixed with visible attribute
