### ISSUE TITLE
CardSettingsDatePicker pt-BR!?

### ISSUE THREAD

**Issue by alexporthal** [codegrue/card_settings#36]
Hello,

How to format the CardSettingsDatePicker component to the default pt-BR?

Thank you

**Comment by AppleEducate** [comment]
what do you mean `pt-BR`?

**Comment by alexporthal** [comment]
format portuguese - Brazil

**Comment by AppleEducate** [comment]
@alexporthal Would you be able to do a pull request? I haven't work with internalization too much.

**Comment by codegrue** [comment]
If anyone is able to internationalize this library it would be great. Please note the issue may lie in flutter_material_pickers instead though.

**Comment by codegrue** [comment]
The next release has a dateFormat property where you can provide the formatting for how you want the date to appear. Release 1.9.0
