### ISSUE TITLE
Validator is not working for CardSettingsMultiselect

### ISSUE THREAD

**Issue by KarthikReddyD** [codegrue/card_settings#42]
I tried to create a Multiselect widget with CardSettingsMultiselect and tried to validate it, but it is not working.

Below is the code snippet for CardSettingsMultiselect:

  CardSettingsMultiselect _buildCardSettingsLanguage() {
    return CardSettingsMultiselect(
      label: 'Language',
      initialValues: <String>['English'],
      options: <String>[
        'English',
        'French',
        'German',
      ],
 
      validator: (List<String> value) {
        if (value == null || value.isEmpty)
          return 'You must pick at least language.';

        return null;
      },
    );
  }

The validator is not showing the error message. Can anyone help on this issue?

**Comment by codegrue** [comment]
Fixed in 1.2.5
