### ISSUE TITLE
Is it possible to make dynamic for label show or not show, as well as labelWidth ?

### ISSUE THREAD

**Issue by NTMS2017** [codegrue/card_settings#43]
I hacked the CardSettingsListPicker label and CardSettingsField labelWidth properties to disable the label. So I can load long named banks list. Example "Bank of America Merrill Lynch International Limited (UK)". 

So, is it possible to make dynamic for label show or not show, as well as labelWidth?
Every time I update my card_settings plugin, I have to manually hacked the code to disable label and labelWidth.

**Comment by codegrue** [comment]
If you are unable to create a pull request, can you please post an example of your disable code here?

**Comment by AppleEducate** [comment]
If you do not want to show the label you can pass in an empty string to the label property. I will look into the label widget. Can you post the code you did to hack it?

**Comment by NTMS2017** [comment]
Not exactly. Because if I pass empty string for label the CardSettingsListPicker dialog picker cannot show the header. So, made this changes:

1) CardSettingsListPicker: this.label,
2) CardSettingsField: this.label,
3) CardSettingsField: this.labelWidth = 20.0,
4) CardSettingsField: I comment the _buildLabel  in Widget _buildLabelRow(BuildContext context) //_buildLabel(context),
