### ISSUE TITLE
Allow customisation of dialog title for CardSettingsMultiselect

### ISSUE THREAD

**Issue by MrNicodemuz** [codegrue/card_settings#46]
The title for the dialog is hardcoded. Can this be changed?

https://github.com/codegrue/card_settings/blob/2d3316d6de615e680845d0465bf19086fc114972/lib/widgets/selection_fields/card_settings_multiselect.dart#L76

**Comment by AppleEducate** [comment]
No, it is an optional parameter passed in as `label:`
