### ISSUE TITLE
Am I supposed to be getting errors here?

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [codegrue/card_settings#47]
Is it just me or is this throwing all sorts of errors for you too?
<img width="1440" alt="screen shot 2019-02-14 at 8 02 10 pm" src="https://user-images.githubusercontent.com/23037821/52833791-8c14a600-3093-11e9-8a19-6b8b13dc06e9.png">

**Comment by AppleEducate** [comment]
This is fixed on the latest version 1.3.0

**Comment by ThinkDigitalRepair** [comment]
OK, thank you
