### ISSUE TITLE
Some missing features (for me)

### ISSUE THREAD

**Issue by Skquark** [codegrue/card_settings#5]
I really like the look and ease of this package, and got it looking fairly good, but ran into a few little limitations that might keep me from replacing my standard Material Input fields.  First problem is I didn't have access to the field's controller which I use to load the data from Firestore after the page is loaded, so I can't just use initalValue to populate it.  Should be simple to have an option property to link it to a saved controller.
I also needed to option to override the default CardSettingsField's label TextStyle from the themedata to a custom one for some of the input field labels that need it.  Also shouldn't be hard, I can see where I'd do it in buildLabel() with an optional labelTextStyle in there.  I particularly needed it for the CardSettingsHeader where I really needed to change the text color because it didn't show up with the Header background color I have.
It would also be nice to be able to align the input fields to the right, instead of it hugging the label on the left.  Most of the fields would look much better right justified in my opinion, but should be a choice..
I could think of a few other things to improve this great component, but these are my more critical needs so I can use it throughout my app.  One part I was trying to figure out it how to make a height field with feet and inches together, not with feet as a decimal, but I can probably figure out how to make a custom CardSettings component for that.  Anyways, thanks.. If you wanted me to help make those changes, I could, but I wouldn't want to impose on your code....

**Comment by codegrue** [comment]
These seem pretty logical and easy. I should be able to make them tonight. I am planning to remove the textformfields so we can get the onchanged event from the textfield, so these will all be more controller based.

Could you please make issues for each so I can track status?

Also, I would like to know how you are using controller to bind to firestore since I am doing it now through initialvalue.

Jeff
________________________________

**Comment by codegrue** [comment]
I am also fine with adding you as a contributor. I know the themabity needs attention so it would be great to have someone give that some love.
________________________________

**Comment by codegrue** [comment]
I made most of your changes and am about to release a new version. Check that out. Regarding the feet and inches, I am planning to do a "multipicker" that would allow this concept. It's on the futures list but probably won't happen until some more overall refinements are made.

**Comment by Skquark** [comment]
Very cool, thanks..  I'm kinda thinking the theme settings should be a property in the parent CardSettings( component so you can set the options for all of the children at once, and be able to override that in the individual fields.  Would make sense instead of relying on the app's theme.
Regarding your question of how I use the controllers with Firestore, I first set up it up for each of the fields like this:
final TextEditingController _controlName = new TextEditingController();
Then in my getData init function, after I get the DocumentSnapshot and go through populating with the data, I simply use _controlName.text = snapshot.data["name"]??""; for each of the stored values.
Anyways, thanks for the updates your making, looking forward to getting it integrated with the next versions....

**Comment by codegrue** [comment]
Look at the new readme. By wrapping CardSettings in a Theme you can target just this control set and get the behaviour you are looking for.

**Comment by codegrue** [comment]
Does attaching the snapshot to controller.text provide bi-directional sync? I wouldn't think so because snapshot is read only from what I understand, so this should behave the same as using initialValue.

**Comment by Skquark** [comment]
Great, got the update and can now do what I needed with the controllers, thanks.  Playing with some of the other changes, but it's not quite there yet.  You added the labelAlign, but what we need is an inputAlign for all the field types.  I kinda like the labelSuffix, works well with a ":"..  
I thought it needed labelStyle and inputStyle in place, but looks like we can handle all that with the Theme wrapper now.  I'm still figuring out the ThemeData mapping.  It took me a bit of time to discover that to change the input text style, it was inside: TextTheme(body1: TextStyle(color: Colors.blue.shade900), and subhead: which should be added to the example doc.  Might also want to show iconTheme to change color of the dropdown arrow and stuff.
Thanks again, got a lot of work ahead of me to put together a bunch of forms, but this ui package makes it much nicer..

**Comment by codegrue** [comment]
Added more styling support and support for input alignment. Not sure the results look great so feedback welcome.
