### ISSUE TITLE
In the new version 1.4.0, validate broke

### ISSUE THREAD

**Issue by GrigK** [codegrue/card_settings#52]
Subj :(

**Comment by AppleEducate** [comment]
Valitor for material or iOS?

**Comment by AppleEducate** [comment]
Not sure if you saw the changelog:

[Warning] For the text fields on iOS using [CupertinoTextFields] the [validator] and [onSaved] do not exist, please use [showErrorIOS] to show a [red] Border around the Text Field and [onChanged] and [onFieldSubmitted] to update the value like in the example.

I am working on finding new ways around this but that is where it is at right now. You can always override with material and it should work.

**Comment by yokiran** [comment]
I tried the sample in 1.4.0 on Android, form.validate() is always returning true.

**Comment by AppleEducate** [comment]
I’m working on the form validation, there was a major refactor.

**Comment by chorauoc** [comment]
Same here , form validations are not working, it is always return true , can you check this issues

**Comment by chorauoc** [comment]
Also form rest button is not rest the elements

**Comment by ThinkDigitalSoftware** [comment]
> Not sure if you saw the changelog:
> 
> > [Warning] For the text fields on iOS using [CupertinoTextFields] the [validator] and [onSaved] do not exist, please use [showErrorIOS] to show a [red] Border around the Text Field and [onChanged] and [onFieldSubmitted] to update the value like in the example.
> 
> I am working on finding new ways around this but that is where it is at right now. You can always override with material and it should work.

Even on iOS with `showMaterialIOS: true,`

**Comment by codegrue** [comment]
showErrorIOS is deprecated in next release [1.7.0] and validation is consolidated. This is probably the cause of this issue.
