### ISSUE TITLE
value not changing -- please help

### ISSUE THREAD

**Issue by tegab** [codegrue/card_settings#53]
CardSettingsListPicker(
                                    options: <String>['unit ', '/lb', '/oz'],
                                    label: 'Type',
                                    autovalidate: _autoValidate,
                                    initialValue: widget.type=="grocer"? info.data["type"]: "",
                                    onChanged: (value) {
                                     setState(() {
                                        _dataModel.type = value;
                                     });
                                    },
                                    onSaved: (value) => _dataModel.type = value,
                                  ),

when i change value on ui, it doesn't reflect on the ui.  setsTATE

**Comment by AppleEducate** [comment]
``` dart
CardSettingsListPicker(
options: ['unit ', '/lb', '/oz'],
label: 'Type',
autovalidate: _autoValidate,
initialValue: _dataModel.type,
onChanged: (value) {
setState(() {
_dataModel.type = value;
});
},
onSaved: (value) => _dataModel.type = value,
),
```

try this

**Comment by tegab** [comment]
got it resolved.  thnx

**Comment by AppleEducate** [comment]
Perfect!
