### ISSUE TITLE
Selected item in List Picker is too big

### ISSUE THREAD

**Issue by yokiran** [codegrue/card_settings#54]
How can I control the font/size of the selected item in CardSettingsListPicker.
![image](https://user-images.githubusercontent.com/47539380/53514796-61582380-3a7d-11e9-8de9-e28c79bfd417.png)

**Comment by yokiran** [comment]
My mistake. TextTheme. headline is being used for this.

**Comment by JiweiMaster** [comment]
do you know how to set the height of dialog which poped by CardSettingsListPicker??? 
I think the interface of this dialog a bit ugly
