### ISSUE TITLE
Any reason why card settings can't be used for normal data entry forms?

### ISSUE THREAD

**Issue by yokiran** [codegrue/card_settings#56]
The name of the package sounds like the scope is limited to card settings. After playing around a bit, it seemed to me like it can be used for any data entry form. I understand that the look and feel is a hybrid of material and cupertino, and that the design was primarily for Settings. A couple of questions

1. Do you see any reason why this package can't be used for any data entry form (ignore look and feel)
2. What will it take to make the fields look like the following? Is this something you plan on?
![image](https://user-images.githubusercontent.com/47539380/53533088-5073d600-3aae-11e9-89a6-b0a4320819bd.png)

I really enjoyed evaluating this package. Easy to implement, good docs/sample, good coverage of field types, good coverage of functionality for each field type, no issues so far besides those that are already logged. Very good work. Thanks

**Comment by codegrue** [comment]
Not at all it's actually built for that.
