### ISSUE TITLE
Feature request: List Picker with key/value

### ISSUE THREAD

**Issue by yokiran** [codegrue/card_settings#60]
The CardSettingsListPicker has an Options attribute that allows List<String>. Can this be enhanced to allow a Map of Key/Values. The requirement is to be able to separate the Value that is displayed in the List from the Key that is stored. For example, I want to display a list with values Male, Female, Unknown. But store only the keys M, F, U. 

If there is already a way to do this, I'd appreciate it if you can explain how.
Thanks

**Comment by Purus** [comment]
Graet that someone created this issue. I am looking for this similar feature.

How this can be done? Any help will be useful. Thanks in advance.

**Comment by Purus** [comment]
Any help on this?

**Comment by codegrue** [comment]
Looks like this would not be too difficult to add. Is it still a current need?

**Comment by codegrue** [comment]
Added in 1.5.3
