### ISSUE TITLE
Version 1.4.1 the validation still broken

### ISSUE THREAD

**Issue by iHunterX** [codegrue/card_settings#61]
As the subject, for now the validation wont work with material on both ios and android, i tried to download and debug it but it seem fine the validator instance is there, the form is fine but validator always return true no matter what... can you please take a look at this? much appriciated

**Comment by Robouste** [comment]
Any workaround for this ?

**Comment by JohnKuan** [comment]
I have tried this, but it does not seem to work.  
https://stackoverflow.com/questions/54848639/flutter-custom-formfield-validate-and-save-methods-are-not-called

**Comment by Hyun-Sik** [comment]
I have the same problem.
I solved it temporarily with build () fix.
@override
   Widget build (BuildContext context) {
     super.build (context);
     ....
}

**Comment by ThinkDigitalSoftware** [comment]
I'm having this issue as well. A regular form field validates, but a card settings one doesn't

**Comment by NTMS2017** [comment]
@Hyun-Sik  super.build (context); gives me an error as shown below. How to achieve that?

error: The method 'build' is always abstract in the supertype. (abstract_super_member_reference at

**Comment by jasonlaw** [comment]
Same for me, the validation is not working, worst is, the onSaved also not triggered.

**Comment by jasonlaw** [comment]
I have tried to fix for one control and it seems working, here is how I changed on CardSettingsText control.

In class _CardSettingsTextState, I removed the build override and make it private.
![image](https://user-images.githubusercontent.com/107820/61798943-c8c3a500-ae5c-11e9-95b0-470dadf8f930.png)

In class CardSettingsText super constructor I called the private _build instead of returning the widget.
![image](https://user-images.githubusercontent.com/107820/61799044-f4df2600-ae5c-11e9-8a67-bbae439bf83b.png)

With the changes, now both validator and onsaved are working in my android emulator. I am using flutter 1.7.8+hotfix 3.

Not sure if this is the correct fixed, really hope it will be fixed asap since I don't really keen in maintaining my own copy of version.

**Comment by codegrue** [comment]
Would you be willing to submit a pull request to have these changes merged in? I don't have the bandwidth to work on this project currently.

**Comment by jasonlaw** [comment]
Sure, a PR has been made.
Thank you for this great package, really appreciate it.

**Comment by kormemis** [comment]
still not working with this solution

> I have tried to fix for one control and it seems working, here is how I changed on CardSettingsText control.
> 
> In class _CardSettingsTextState, I removed the build override and make it private.
> ![image](https://user-images.githubusercontent.com/107820/61798943-c8c3a500-ae5c-11e9-95b0-470dadf8f930.png)
> 
> In class CardSettingsText super constructor I called the private _build instead of returning the widget.
> ![image](https://user-images.githubusercontent.com/107820/61799044-f4df2600-ae5c-11e9-8a67-bbae439bf83b.png)
> 
> With the changes, now both validator and onsaved are working in my android emulator. I am using flutter 1.7.8+hotfix 3.
> 
> Not sure if this is the correct fixed, really hope it will be fixed asap since I don't really keen in maintaining my own copy of version.

**Comment by loledesma** [comment]
I have the same issue. OnSave is doesnt trigger.

**Comment by codegrue** [comment]
In the example app, validation and onsave works as expected. Can someone comment on if they are still seeing this not working in 1.5.0+ of card_settings?

**Comment by enricobenedos** [comment]
This is my test page with last package version `1.6.1`
```dart
import 'package:card_settings/card_settings.dart';
import 'package:flutter/material.dart';
import 'package:wamii_app/widgets/widgets.dart';

class ContactsPage extends StatefulWidget {
  ContactsPage({Key key}) : super(key: key);

  @override
  _ContactsPageState createState() => _ContactsPageState();
}

class _ContactsPageState extends State<ContactsPage> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final GlobalKey<FormState> _nameKey = GlobalKey<FormState>();
  String _name;
  String _surname;
  String _email;
  String _message;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: myAppBar(),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: CardSettings(
            key: _formKey,
            children: <Widget>[
              CardSettingsText(
                showMaterialonIOS: true,
                key: _nameKey,
                label: 'Name',
                icon: Icon(Icons.person),
                requiredIndicator:
                    Text('*', style: TextStyle(color: Colors.red)),
                autovalidate: true,
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Name is required.';
                  return null;
                },
                //showErrorIOS: _ponyModel.name == null || _ponyModel.name.isEmpty,
                onSaved: (value) => _name = value,
                // onChanged: (value) {
                //   setState(() {
                //     _ponyModel.name = value;
                //   });
                //   _showSnackBar('Name', value);
                // },
              ),
              CardSettingsText(
                showMaterialonIOS: true,
                //key: _nameKey,
                label: 'Surname',
                icon: Icon(Icons.person),
                requiredIndicator:
                    Text('*', style: TextStyle(color: Colors.red)),
                autovalidate: true,
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Surname is required.';
                  return null;
                },
              ),
              CardSettingsEmail(
                showMaterialonIOS: true,
                labelWidth: 150.0,
                // key: _emailKey,
                icon: Icon(Icons.mail),
                autovalidate: true,
                validator: (value) {
                  if (value == null || value.isEmpty)
                    return 'Email is required.';
                  else {
                    final bool isEmailOk = RegExp(
                            r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+")
                        .hasMatch(value);
                    if (!isEmailOk) {
                      return 'Wrong email!';
                    } else {
                      return null;
                    }
                  }
                },
                // onSaved: (value) => _ponyModel.email = value,
                // onChanged: (value) {
                //   setState(() {
                //     _ponyModel.email = value;
                //   });
                //   _showSnackBar('Email', value);
                // },
              ),
              CardSettingsParagraph(
                label: 'Message',
                icon: Icon(Icons.textsms),
              ),
              CardSettingsButton(
                label: 'Send',
                onPressed: () {}, //async => await _sendEmail(),
              )
            ],
          ),
        ));
  }
}
```
`onSaved` seems to not work. Am I missing some code? When `onSaved` is fired?

**Comment by codegrue** [comment]
Look at the example. CardSettings needs to be inside a “Form” widget. The Form widget has all the save and submit logic.

**Comment by codegrue** [comment]
Your example lacks a Form widget. CardSettings does layout, but doesn't process saves or validations. Please see the example app for suggested structure.
