### ISSUE TITLE
CardSettings - Elevation not working

### ISSUE THREAD

**Issue by Robouste** [codegrue/card_settings#63]
First, I'd like to tell how awesome I think this plugin is !

I see that CardSettings has a cardElevation property but it doesn't do anything.

```JS
CardSettings.sectioned(
      cardElevation: 12, // => doesn't seem to change anything
      children: <CardSettingsSection>[
        CardSettingsSection(
            header: CardSettingsHeader(
              label: "Box details",
              color: CustomColors.primary,
            ),
            children: <Widget>[
              // list of widget
            ])
      ],
    )
```

**Comment by codegrue** [comment]
Fixed in release 1.5.2. Remember to use in conjunction with padding. elevation only controls how much shadow you see, but you need space also for it to be visible.
