### ISSUE TITLE
card_settings_text.dart:272 TextAlign use const TextAlign.end

### ISSUE THREAD

**Issue by superyyl** [codegrue/card_settings#64]
![image](https://user-images.githubusercontent.com/1296024/56725415-6553a980-677f-11e9-8ba8-0680d741be55.png)

Should use widget?.contentAlign

**Comment by JohnKuan** [comment]
Hi @codegrue,

This is also a problem for my use case. If you are open for PR, do reply on this issue as this repo has not be updated for some time.

**Comment by codegrue** [comment]
Sure please do a pull request.
