### ISSUE TITLE
CardSettingsDatePicker to accept a DateFormat in param

### ISSUE THREAD

**Issue by JohnKuan** [codegrue/card_settings#65]
Hi @codegrue, thanks for maintaining this library. I have a suggestion, would it be simple to add a DateFormat param in CardSettingsDatePicker? I noticed that there is a `justDate` param and by default it is false, but it will not make sense if `justDate` is by default false and yet the default DateFormat does not display the time of day component in DateTime after selection.

**Comment by Bujupah** [comment]
#96  I've made some changes regarding that, hope @codegrue check them out

**Comment by codegrue** [comment]
Added. Will be in release 1.9.0
