### ISSUE TITLE
issues with flutter_colorpicker

### ISSUE THREAD

**Issue by JohnKuan** [codegrue/card_settings#66]
There is a compiler issue after flutter_colorpicker updated their repo. 

`Error: Too few positional arguments: 2 required, 0 given.
                child: ColorPicker(
                                  ^
`

**Comment by sashko** [comment]
I've managed to go around the problem by fixating `flutter_colorpicker` version to `0.2.1`:

Change the following line in `pubspec.yaml` of the plugin:

    flutter_colorpicker: ^0.2.1

to

    flutter_colorpicker: 0.2.1

**Comment by matanshukry** [comment]
I couldn't replicate this issue.
Possibly they changed the constructor to use non-positional arguments again?

**Comment by codegrue** [comment]
Current release works with flutter_colorpicker: ^0.2.6
