### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by pouledodue** [codegrue/card_settings#67]
Make it compatible with Flutter Web

in vscode...
`Flutter: New Web Project` ..

**Comment by codegrue** [comment]
I have not tried using Flutter Web yet. What happens when you try to use this library?

**Comment by NiranjanShah** [comment]
Unsupported operation: Platform._operatingSystem

**Comment by codegrue** [comment]
Just checked in a flutter web compatible build. Please test if able to. Will release to production in a few days. the version will be 1.9.0

**Comment by CoolONEOfficial** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/18753760/82616883-2d63a380-9bd7-11ea-8e7a-43a6dd15f251.png">
All works cool, but you forgot to add web compatible badge on pub.dev
