### ISSUE TITLE
CardSettingsListPicker in android platform

### ISSUE THREAD

**Issue by JiweiMaster** [codegrue/card_settings#68]
the dialog of CardSettingsListPicker poped is very large ,how can I customise or modify the height of the dialog 
![Screenshot_2019-06-04-11-28-28-968_com example flutter_module host](https://user-images.githubusercontent.com/25447446/58849193-0d805a80-86bc-11e9-8815-0998a385eac6.png)

**Comment by JiweiMaster** [comment]
t

CardSettingsListPicker(
          showMaterialIOS: _showMaterialIOS,
          label: '是否收费',
          initialValue: list[position].isCharged,
          options: ['收费', '不收费'],
          //  key: _cityKey,
          onChanged: (value) {
            list[position].isCharged = value;
            materialItemsController.sink.add(list);
          },
        ),

**Comment by codegrue** [comment]
I believe this is the standard Material design style. I would have to add a property you can set if you absolutely need to do this.

**Comment by codegrue** [comment]
The ability to restrict the size will be in release 1.9.0

**Comment by acamenhas** [comment]
Can you give me a small example?
