### ISSUE TITLE
CardSeittings is not working in Expanded View

### ISSUE THREAD

**Issue by amanshaw38** [codegrue/card_settings#69]
Hi,
I was using Cards in Expanded view to show details after I came to know about CardSettings I implemented it, but it looks like CardSettings is not returning anything.

Small Snippet of my code:

isExpanded: item['expanded'],
                body: Form(
                    child: CardSettings(
                      labelAlign: TextAlign.right,
                  labelSuffix: ':',
                  labelPadding: 10.0,
                  contentAlign: TextAlign.left,
                  children: <Widget>[
                    CardSettingsHeader(label:'Details'),
                    CardSettingsText(
                      label: 'Transaction Name',
                      initialValue: item['split'].transaction.name,
                    ),
                    CardSettingsText(
                      label: 'Category',
                      initialValue:
                          item['split'].transaction.category.toString(),
                    )
                  ],
                )),
              );
            }).toList(),
          ),

<img width="186" alt="abc" src="https://user-images.githubusercontent.com/26847623/61582346-665e6200-ab47-11e9-8ccc-54ae4893dd55.png">

**Comment by codegrue** [comment]
I wouldn't recommend using it for this purpose. It's designed to be a data entry form, not a list formatter.
