### ISSUE TITLE
Add MultiSelect widget

### ISSUE THREAD

**Issue by codegrue** [codegrue/card_settings#7]
Widget that allows a bunch of choices from a checkbox list.

**Comment by codegrue** [comment]
Added in release 0.1.16

**Comment by DanMossa** [comment]
Any quick example on how to use?

```
List<String> categoryList = ["Dogs", "Cats", "Birds"];

CardSettingsMultiselect(
                label: "Categories",
                options: categoryList,
              ),
```
Throws me an error with 

> I/flutter (28608): The following NoSuchMethodError was thrown building CardSettingsMultiselect(dirty, state:
> I/flutter (28608): _CardSettingsMultiselectState#4cff0):
> I/flutter (28608): The method 'map' was called on null.
> I/flutter (28608): Receiver: null
> I/flutter (28608): Tried calling: map<Chip>(Closure: (String) => Chip)

**Comment by codegrue** [comment]
Hmmm. Maybe the initialValues needs to be an empty array. If so this would be a bug. Can you confirm by making initialValues not null?

  CardSettingsMultiselect _buildCardSettingsMultiselect() {
    return CardSettingsMultiselect(
      key: _hobbiesKey,
      label: 'Hobbies',
      initialValues: _ponyModel.hobbies,
      options: allHobbies,
      onSaved: (value) => _ponyModel.hobbies = value,
      onChanged: (value) => _showSnackBar('Hobbies', value),
    );
  }
