### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by jasonlaw** [codegrue/card_settings#73]
When running the example model, I keep getting the error.

![image](https://user-images.githubusercontent.com/107820/61993989-51ce1c80-b0a7-11e9-8ca3-aceba77c58fb.png)

I am using flutter 1.7.8 hotfix3.

**Comment by codegrue** [comment]
Can you try with the latest release?

**Comment by codegrue** [comment]
Closing unless you report back it's still now working
