### ISSUE TITLE
CardSettingsRadio Form widget?has?or not?

### ISSUE THREAD

**Issue by zengfr** [codegrue/card_settings#77]
CardSettingsRadio Form widget?has?or not?

**Comment by codegrue** [comment]
It does not yet have such a control. Might be easy to abstract from the multiselect however.

**Comment by codegrue** [comment]
The new dialog library this uses has a radio dialog. Just need to wrap it in a new control.

**Comment by codegrue** [comment]
Added. Will be in release 1.9.0
