### ISSUE TITLE
How to remove label and move text content to left?

### ISSUE THREAD

**Issue by NTMS2017** [codegrue/card_settings#78]
Hi,

I need to remove label and move text content to left. I need to leave indicator on left and after that I need to start the text content. Currently text content is on middle. How to remove label and move text content to left? Thanks

**Comment by codegrue** [comment]
try setting the label text to "" and the labelWidth to 0. Report back because I have not tested this.

**Comment by codegrue** [comment]
I tested and it works with these settings:

```
      label: '',
      labelWidth: 0.0,
```
