### ISSUE TITLE
your _showSnackBar value shows on top of the keyboard and mine doesn't?

### ISSUE THREAD

**Issue by NTMS2017** [codegrue/card_settings#79]
your _showSnackBar value shows on top of the keyboard and mine doesn't. Any idea or special configuration? I am using stable release version of flutter 1.9.1 hot fix 4. Thanks

**Comment by codegrue** [comment]
Nothing special being done that I know of. Can you confirm if you were able to fix or if it's working in the latest release?

**Comment by NTMS2017** [comment]
still same issue

**Comment by codegrue** [comment]
By on top, do you mean vertically above the keyboard, or do you mean obscuring the keyboard?

**Comment by codegrue** [comment]
Please run the sample app and report if you see this behavior because it works correctly there.
