### ISSUE TITLE
How can I change the label with?

### ISSUE THREAD

**Issue by winsonet** [codegrue/card_settings#80]
The label with is so much so that can't see the content, how can I change it?
![image](https://user-images.githubusercontent.com/1869995/68818301-8bab4900-06bf-11ea-87c4-d9e8dbf2ecc0.png)
for that case, the email can't show

**Comment by supertrens** [comment]
I don't totally understand your request, however, I can get your email in my `CardSettingsEmail`. But be aware that the maximum length for an email is 30 by default , if you want to allow longer length change the maxLength property. Here is  the code for the example in the screenshot

**Comment by winsonet** [comment]
oh, thanks a lot!

**Comment by codegrue** [comment]
Adding a global labelWidth setting as well. Coming soon.

**Comment by codegrue** [comment]
added in 1.5.0
