### ISSUE TITLE
Error: The method 'dependOnInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.

### ISSUE THREAD

**Issue by ayodiya** [codegrue/card_settings#83]
Every time I try to debug i get this error,  **Error: The method 'dependOnInheritedWidgetOfExactType' isn't defined for the class 'BuildContext'.**
 **I have tried lots of method to solve it cant find my way around it.**

**This is the code**
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:card_settings/card_settings.dart';

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

 
  

class _LoginPageState extends State<LoginPage> {
String title = "Spheria";
  String author = "Cody Leet";
  String url = "http://www.codyleet.com/spheria";
 
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  
  static LoginPage of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LoginPage>();
  }
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    body:  Form(
        key: _formKey,
        child: CardSettings(
          children: <Widget>[
            CardSettingsHeader(label: 'Favorite Book'),
            CardSettingsText(
              label: 'Title',
              initialValue: title,
              validator: (value) {
                if (value == null || value.isEmpty) return 'Title is required.';
              },
              onSaved: (value) => title = value,
            ),
            CardSettingsText(
              label: 'URL',
              initialValue: url,
              validator: (value) {
                if (!value.startsWith('http:')) return 'Must be a valid website.';
              },
              onSaved: (value) => url = value,
            ),
          ],
        ),
    ), 
    );
  }
}

**Used it in this here
Pls ignore extra brackets**

import 'package:domesms/screens/Login.dart';
import 'package:flutter/material.dart';

class MyHomePage extends StatefulWidget {
   final  String title ;

  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    
    
        return Scaffold(
          appBar: AppBar(title: Text('DOMESMS.COM')),
          body: Center(child: Text('My Page!')),
          drawer: Drawer(
            // Add a ListView to the drawer. This ensures the user can scroll
            // through the options in the drawer if there isn't enough vertical
            // space to fit everything.
            child: ListView(
              // Important: Remove any padding from the ListView.
              padding: EdgeInsets.zero,
              children: <Widget>[
                UserAccountsDrawerHeader(
                accountName:  Text('Oludiya Ayodeji'),
                 accountEmail:Text('ayodiya@gmail.com'),
                 currentAccountPicture: CircleAvatar(
                   backgroundImage: AssetImage('images/unisexavatar.png',),
                   backgroundColor: Colors.white,
                   radius: 80
                 ),
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
            ),
            ListTile(
              leading: Icon(Icons.person,
              color: Colors.cyanAccent),
              title: Text('ACCOUNT DETAILS'),
              onTap: () {
                // Update the state of the app
                // ...
                // Then close the drawer

                Navigator.pop(context);
                Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => **LoginPage()**));
                
              },
            ),
  }
}

**Comment by codegrue** [comment]
Are you on the latest stable release of Flutter? This replaced a deprecated method.

**Comment by ayodiya** [comment]
Solved by upgrading to the latest flutter
