### ISSUE TITLE
Freeze during scrolling

### ISSUE THREAD

**Issue by eastrd** [codegrue/card_settings#84]
Hi, Thank you so much for the amazing set of widgets.

I have a minor problem, there seems to be a bug in `CardSettingsNumberPicker` where if you try to scroll during another scroll animation, the entire scroll box would freeze. (Although the "Cancel" and "Ok" buttons are still clickable and operating).

I believe this is the same issues as https://github.com/flutter/flutter/issues/14452 and https://github.com/flutter/flutter/issues/11433 . 
The latter issue has also provided a screen recording to replicate the exact same issue that I have with `CardSettingsNumberPicker`.

The error message is `'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 496 pos 12: '_hold == null': is not true.`.

I was wondering if there are any solutions for this problem?

**Comment by codegrue** [comment]
Did this just start happening over the last couple of days? I removed a scroll related line that was providing warning but it might have been handling this condition.

**Comment by eastrd** [comment]
I can't tell, I only started using this library since yesterday.

**Comment by eastrd** [comment]
The same issue always exists in `CardSettingsListPicker`

**Comment by Tonku** [comment]
Any update?

**Comment by eastrd** [comment]
@Tonku  Nope

**Comment by NTMS2017** [comment]
I am trying to update my app and still waiting solution. Any update yet?

**Comment by codegrue** [comment]
I extracted the pickers into a separate library and will be publishing that soon. I believe the fix for this will be in that. card_settings will incorporate those soon thereafter,
