### ISSUE TITLE
the label width issue for CardSettingsSwitch

### ISSUE THREAD

**Issue by winsonet** [codegrue/card_settings#86]
I also find there is an label width issue for CardSettingsSwitch, please see below:

![image](https://user-images.githubusercontent.com/1869995/71759715-f7ee4000-2eeb-11ea-80c3-4aeb392f4e3c.png)

my code:
```
              CardSettingsSwitch(
                    label: 'Always use photo location?',
                    trueLabel: '',
                    falseLabel: '',                    
                    initialValue: usePhotoLocation,
                    onSaved: (value) => usePhotoLocation = value,
                    onChanged: (value) {
                      setState(() {
                        usePhotoLocation = value;
                      });
                    },
                  ),
```
the lable so long so can't display, how can I handle it?

thanks!

**Comment by codegrue** [comment]
It's because all labels have the same width. In the case of the switch control, the state text appears right after the label left justified with the other controls.  I'll see if this can be made a per control setting.

**Comment by codegrue** [comment]
Published a fix and updated the example to show this. Version 1.5.4

**Comment by winsonet** [comment]
thanks a lot, it can be set the label width now, but if the label to long, the problem still happen :(
![image](https://user-images.githubusercontent.com/1869995/71904806-cdc5a800-31a1-11ea-89c1-955b9d4c55d4.png)
Can it allow max line for the label or it will auto wrap to second line?

Thanks!
