### ISSUE TITLE
Allow customization of CardSettingsMultiselect title

### ISSUE THREAD

**Issue by BjoernPetersen** [codegrue/card_settings#88]
The `CardSettingsMultiselect` class has a `label` argument, but it's prepended by the hard-coded String 'Select '.

https://github.com/codegrue/card_settings/blob/532a4935fc259d29b8d15693622e0d5191ce1369/lib/widgets/selection_fields/card_settings_multiselect.dart#L77

The hard-coded String makes it impossible to localize the widget. I propose dropping the prefix and replacing the default value for `label` (literally "Label", which is probably never the right choice) with "Select".

**Comment by codegrue** [comment]
Fixed on version 1.7.0
