### ISSUE TITLE
Responsive form

### ISSUE THREAD

**Issue by arthurgustin** [codegrue/card_settings#9]
Hi there,
I'm building a multi-step form for my application for days before searching the internet to find your library.
I can't test it yet because I'm at work but I really want to use it for my project as it would simplify many things.
My question is: is your library able to displays two elements side-by-side in landscape mode, or if the screen has a large resolution (like in tablets), I've dig in the code a bit and did not find this information.

Anyway, it seems like you have done an amazing job so I thank you for that :)

**Comment by codegrue** [comment]
No support has been added for landscape. I just tested it and it expands the fields to full width. I think you could make two of them in a Row widget and would get them side by side. If you experiment and find a solution or ideas let me know.

**Comment by arthurgustin** [comment]
My use-case is the following:
  - 1 column in small screens (like the examples you provided)
  - 2 columns in large screens (only fields, not headers)

After playind around with the code, here is what I came up with: I wrap my tuple of widget with this function:

```dart
Widget TeddyLayoutBuild(Widget child1, Widget child2) {
    return LayoutBuilder(
      builder: (context, constraints) {
        double maxWidthToUse = constraints.maxWidth;
        if (constraints.maxWidth > 600) {
          maxWidthToUse = constraints.maxWidth / 2;
        }
        return Wrap(
          children: <Widget>[
            ConstrainedBox(
              constraints: BoxConstraints(maxWidth: maxWidthToUse),
              child: child1,
            ),
            ConstrainedBox(
              constraints: BoxConstraints(maxWidth: maxWidthToUse),
              child: child2,
            ),
          ],
        );
      },
    );
  }
```
with 1 column:
![1column](https://user-images.githubusercontent.com/27814509/44143245-45a0c9d8-a083-11e8-90a5-52dbf60f9c3a.png)

with 2 columns
![2columns](https://user-images.githubusercontent.com/27814509/44143246-48092314-a083-11e8-9abd-6020dc76ca49.png)

Do you have a better idea ?

**Comment by arthurgustin** [comment]
Yeh I tried with Rows but had errors with because of unbounded height, I'm not a flutter expert so I did not want to spend too much time on it

**Comment by codegrue** [comment]
I got it working with Rows and updated the example to show it switching between portrait and landscape. Row needs each field to be wrapped in an Expanded widget to size properly (or at least so it functions). There may be other techniques as well such as the one you suggested.

I do like your builder function to make this easier and maybe those should be added to the core project for common layouts.
