### ISSUE TITLE
Field icon is always black

### ISSUE THREAD

**Issue by taxpayer** [codegrue/card_settings#94]
Hi, first of all, thanks for the component. It's well built and very helpful.

I started testing it today. migrating a web form to a flutter app. I have some fields where the users can input their social networks, and I have a coloured icon for each one. I tried to do the same with the icon attribute, but it only shows in black:

`
return CardSettingsText(label: 'Whatsapp', icon: Icon(FontAwesomeIcons.whatsappSquare, color: Colors.green));
`

Thanks.

**Comment by codegrue** [comment]
Fixed in next release 1.9.0
