### ISSUE TITLE
Strange behavior when setting inputDecorationTheme and  textTheme at same time

### ISSUE THREAD

**Issue by rubgithub** [codegrue/card_settings#97]
If only `inputDecorationTheme` is setting works fine, but after adding `textTheme` the text color looks change to white (labels, picker and input)

```
inputDecorationTheme: InputDecorationTheme(
          labelStyle: TextStyle(
            fontSize: 10,
          ),
        ),
        textTheme: TextTheme(
          subhead: TextStyle(
            fontSize: 10,
          ),
        ),
```
![image](https://user-images.githubusercontent.com/3399476/81119319-85708980-8ef8-11ea-8ca6-bab19e00909b.png)

![image](https://user-images.githubusercontent.com/3399476/81119259-68d45180-8ef8-11ea-8af1-62940caa17c0.png)

**Comment by codegrue** [comment]
What if you add a color to those styles? I'm thinking it's defaulting to white for some reason.

**Comment by rubgithub** [comment]
I've tried it but 'not selected' items not showing (white color)
```
inputDecorationTheme: InputDecorationTheme(
          labelStyle: TextStyle(fontSize: 14, color: Colors.black),
        ),
        textTheme: TextTheme(
          subhead: TextStyle(fontSize: 14, color: Colors.blue),
        ),
```

```
options: const ['Store1', 'Store2'],
initualValue: 'Store1',
```
![image](https://user-images.githubusercontent.com/3399476/81180316-d45e0380-8f78-11ea-98bc-3931ac4438ac.png)

![image](https://user-images.githubusercontent.com/3399476/81180440-0a9b8300-8f79-11ea-9dd6-d30b13e3520d.png)

**Comment by codegrue** [comment]
I'll play with this tonight. Theming is a PITA in general.

**Comment by codegrue** [comment]
accentColor: Colors.red // picker selections       
textTheme: TextTheme(
     body1: TextStyle(color: Colors.yellow), // picker text
),

**Comment by rubgithub** [comment]
Thank you very much, `subhead` color solved my problem.
